version: '3.8'

# https://docs.docker.com/compose/environment-variables/envvars/#compose_project_name
name: "engine"

services:
  cpp_engine:
    build:
      context: .
      args:
        user:
        uid:
        gid:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]
    #           driver: nvidia
    #           device_ids: ["1"]
    hostname: ${COMPOSE_PROJECT_NAME}
    ports:
      - "33333:22"  # ssh
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/passwd:/etc/passwd  # same password, uid, gid with host
      - /etc/shadow:/etc/shadow
      - /etc/group:/etc/group
      - ../:${HOME}/work/${COMPOSE_PROJECT_NAME}
      - ${HOME}/.bashrc:${HOME}/.bashrc
      - ${HOME}/.ssh:${HOME}/.ssh
      # - ./.jupyter:${HOME}/.jupyter
    entrypoint: /usr/sbin/sshd -D
    restart: always
