MACRO(SUBDIRLIST result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
      LIST(APPEND dirlist ${child})
    ENDIF()
  ENDFOREACH()
  SET(${result} ${dirlist})
ENDMACRO()

MACRO(ADD_CONTESTS)
  # CMakeLists.txt が存在しないサブディレクトリをコンテストとして追加する。
  # サブディレクトリ内のファイルを走査してexecutableを作成する。
  FILE(GLOB children RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/*)
  message("-- ADD BELOW SUBDIRS IN ${CMAKE_CURRENT_SOURCE_DIR} TO CONTEST")
  FOREACH(child IN LISTS children)
    IF(IS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/${child})
      IF(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${child}/CMakeLists.txt)
        message("      ${child}")
        FILE(GLOB file_list "${CMAKE_CURRENT_SOURCE_DIR}/${child}/[a-z]*.cpp")
        FOREACH(fname IN LISTS file_list)
          get_filename_component(bname ${fname} NAME_WE)
          add_executable(${module_name}_${child}_${bname} ${fname})
        ENDFOREACH()
      ENDIF()
    ENDIF()
  ENDFOREACH()
  message("-- END ADD CONTEST")
ENDMACRO()
